// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.avro.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class OrderProduct : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""OrderProduct"",""namespace"":""com.avro.bean"",""fields"":[{""name"":""order_id"",""type"":""int""},{""name"":""price"",""type"":""float""},{""name"":""product_id"",""type"":""int""},{""name"":""product_name"",""type"":""string""},{""name"":""product_price"",""type"":""float""}]}");
		private int _order_id;
		private float _price;
		private int _product_id;
		private string _product_name;
		private float _product_price;
		public virtual Schema Schema
		{
			get
			{
				return OrderProduct._SCHEMA;
			}
		}
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				this._order_id = value;
			}
		}
		public float price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				this._product_id = value;
			}
		}
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				this._product_name = value;
			}
		}
		public float product_price
		{
			get
			{
				return this._product_price;
			}
			set
			{
				this._product_price = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.order_id;
			case 1: return this.price;
			case 2: return this.product_id;
			case 3: return this.product_name;
			case 4: return this.product_price;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.order_id = (System.Int32)fieldValue; break;
			case 1: this.price = (System.Single)fieldValue; break;
			case 2: this.product_id = (System.Int32)fieldValue; break;
			case 3: this.product_name = (System.String)fieldValue; break;
			case 4: this.product_price = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
