// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.avro.bean
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class OrderAgg : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"OrderAgg\",\"namespace\":\"com.avro.bean\",\"fields\":[{\"name\":" +
				"\"order_id\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"float\"},{\"name\":\"product_id\",\"t" +
				"ype\":\"int\"},{\"name\":\"totalPrice\",\"type\":\"float\"}]}");
		private int _order_id;
		private float _price;
		private int _product_id;
		private float _totalPrice;
		public virtual Schema Schema
		{
			get
			{
				return OrderAgg._SCHEMA;
			}
		}
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				this._order_id = value;
			}
		}
		public float price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				this._product_id = value;
			}
		}
		public float totalPrice
		{
			get
			{
				return this._totalPrice;
			}
			set
			{
				this._totalPrice = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.order_id;
			case 1: return this.price;
			case 2: return this.product_id;
			case 3: return this.totalPrice;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.order_id = (System.Int32)fieldValue; break;
			case 1: this.price = (System.Single)fieldValue; break;
			case 2: this.product_id = (System.Int32)fieldValue; break;
			case 3: this.totalPrice = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
