// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: include_confluet_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Streamiz.Kafka.Net.Tests.Helpers.Proto {

  /// <summary>Holder for reflection information generated from include_confluet_type.proto</summary>
  public static partial class IncludeConfluetTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for include_confluet_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IncludeConfluetTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtpbmNsdWRlX2NvbmZsdWV0X3R5cGUucHJvdG8SJlN0cmVhbWl6LkthZmth",
            "Lk5ldC5UZXN0cy5IZWxwZXJzLlByb3RvGh9nb29nbGUvcHJvdG9idWYvdGlt",
            "ZXN0YW1wLnByb3RvGhxjb25mbHVlbnQvdHlwZS9kZWNpbWFsLnByb3RvIlcK",
            "EkluY2x1ZGVDb25mbHVlVHlwZRIRCglJTlRfVkFMVUUYASABKAUSLgoNREVD",
            "SU1BTF9WQUxVRRgKIAEoCzIXLmNvbmZsdWVudC50eXBlLkRlY2ltYWxiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Confluent.Type.DecimalReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Streamiz.Kafka.Net.Tests.Helpers.Proto.IncludeConflueType), global::Streamiz.Kafka.Net.Tests.Helpers.Proto.IncludeConflueType.Parser, new[]{ "INTVALUE", "DECIMALVALUE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class IncludeConflueType : pb::IMessage<IncludeConflueType>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IncludeConflueType> _parser = new pb::MessageParser<IncludeConflueType>(() => new IncludeConflueType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IncludeConflueType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Streamiz.Kafka.Net.Tests.Helpers.Proto.IncludeConfluetTypeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IncludeConflueType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IncludeConflueType(IncludeConflueType other) : this() {
      iNTVALUE_ = other.iNTVALUE_;
      dECIMALVALUE_ = other.dECIMALVALUE_ != null ? other.dECIMALVALUE_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IncludeConflueType Clone() {
      return new IncludeConflueType(this);
    }

    /// <summary>Field number for the "INT_VALUE" field.</summary>
    public const int INTVALUEFieldNumber = 1;
    private int iNTVALUE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int INTVALUE {
      get { return iNTVALUE_; }
      set {
        iNTVALUE_ = value;
      }
    }

    /// <summary>Field number for the "DECIMAL_VALUE" field.</summary>
    public const int DECIMALVALUEFieldNumber = 10;
    private global::Confluent.Type.Decimal dECIMALVALUE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Confluent.Type.Decimal DECIMALVALUE {
      get { return dECIMALVALUE_; }
      set {
        dECIMALVALUE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IncludeConflueType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IncludeConflueType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (INTVALUE != other.INTVALUE) return false;
      if (!object.Equals(DECIMALVALUE, other.DECIMALVALUE)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (INTVALUE != 0) hash ^= INTVALUE.GetHashCode();
      if (dECIMALVALUE_ != null) hash ^= DECIMALVALUE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (INTVALUE != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(INTVALUE);
      }
      if (dECIMALVALUE_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(DECIMALVALUE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (INTVALUE != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(INTVALUE);
      }
      if (dECIMALVALUE_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(DECIMALVALUE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (INTVALUE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(INTVALUE);
      }
      if (dECIMALVALUE_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DECIMALVALUE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IncludeConflueType other) {
      if (other == null) {
        return;
      }
      if (other.INTVALUE != 0) {
        INTVALUE = other.INTVALUE;
      }
      if (other.dECIMALVALUE_ != null) {
        if (dECIMALVALUE_ == null) {
          DECIMALVALUE = new global::Confluent.Type.Decimal();
        }
        DECIMALVALUE.MergeFrom(other.DECIMALVALUE);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            INTVALUE = input.ReadInt32();
            break;
          }
          case 82: {
            if (dECIMALVALUE_ == null) {
              DECIMALVALUE = new global::Confluent.Type.Decimal();
            }
            input.ReadMessage(DECIMALVALUE);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            INTVALUE = input.ReadInt32();
            break;
          }
          case 82: {
            if (dECIMALVALUE_ == null) {
              DECIMALVALUE = new global::Confluent.Type.Decimal();
            }
            input.ReadMessage(DECIMALVALUE);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
