using System;

namespace Streamiz.Kafka.Net.Errors
{
    /// <summary>
    /// <see cref="StreamsException"/> is the top-level exception type generated by Kafka Streams.
    /// </summary>
    public class StreamsException : Exception
    {
        /// <summary>
        /// Constructor with exception message
        /// </summary>
        /// <param name="message">Exception message</param>
        public StreamsException(string message) 
            : base(message)
        {
        }

        /// <summary>
        /// Constructor with inner exception
        /// </summary>
        /// <param name="innerException">Inner exception</param>
        public StreamsException(Exception innerException) 
            : this("", innerException)
        {
        }

        /// <summary>
        /// Constructor with exception message and inner exception
        /// </summary>
        /// <param name="message">Exception message</param>
        /// <param name="innerException">Inner exception</param>
        public StreamsException(string message, Exception innerException) 
            : base(message, innerException)
        {
        }
    }
}
